# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
   imageName: 'pipelines-javascript-docker'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
     repository: $(imageName)
     command: build 
     Dockerfile: app/Dockerfile

  - task: Docker@2
    inputs:
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'
     addBaseImageData: 
     addPipelineData: 
     arguments: 

  - task: DockerCompose@0
    inputs:
     containerregistrytype: 'Container Registry'
     dockerComposeFile: '**/docker-compose.yml'
     action: 'Push services'